### PR TITLE
Add function docs

### PR DESCRIPTION
**Pull request by innovate-invent**
as yaml to allow for structured storage of the signatures

### CODE REVIEW

**Review by springcomp — COMMENTED** [review]
Missing [some functions](https://github.com/jmespath-community/jmespath.site/tree/master/documentation/grammar/functions):

- `items`
- `map`
- `max_by`
- `min_by`
- `sort_by`
- `to_string`
- `zip`
-

**Review by springcomp — COMMENTED** [review]
Maybe we should decide on a consistent naming convention.
I noticed from the `rst` specifications that cross-references to functions is done using symbols containing a hyphen, (_i.e_ `to-string`). So in the JMESPath site, I used this as the file name for the function include files.

Please, consider using a hyphen for file names here as well.

**Comment by innovate-invent** [comment]
items and zip are not included in the spec yet, I am not sure they should be included.

**Comment by springcomp** [comment]
> items and zip are not included in the spec yet, I am not sure they should be included.

You had `from_items` in your commit, that's why included them. We can debate the inclusion on the relevant discussion.

My view was that they were as good as included based on the various discussions in the official repository. There is even a PR that waits to be acceptée.

Happy to discuss further.

**Review by springcomp — APPROVED** [review]
We'll need to rename the target function files with hyphens when generating the spec.

**Comment by innovate-invent** [comment]
Yea, no worries about the file names. I am reworking a lot of it.

**Pull request merged**
