### PR TITLE
fix: issue #173 - find_last example

### LINKED ISSUE #173: find_last exemple is incorrect
The [following example](https://github.com/jmespath-community/jmespath.spec/blob/main/jep-014-string-functions.md#examples-1)  is incorrect:

`` find_last('suject string', 's') `` -> `` 0 ``.

It should evaluate to ``8`` instead.
Library implementations do indeed return the correct result.

### PR DESCRIPTION
**Pull request by cawalch**
fixes #173

### CODE REVIEW

**Review by springcomp — APPROVED** [review]
Thanks for your contribution.

**Comment by springcomp** [comment]
@cawalch  Thank you for your contributions.

I see you have quite an interest in this project.
Would you be interested in [becoming a maintainer](https://github.com/jmespath-community/typescript-jmespath/issues/16) for the TypeScript implementation ?

I’m thinking about about we could take advantage of Deno and various other improvements.
I unfortunately do not have much time at the moment.

**Comment by cawalch** [comment]
> Would you be interested in https://github.com/jmespath-community/typescript-jmespath/issues/16 for the TypeScript implementation ? 

@springcomp I'd be happy to help maintain the project.

> I’m thinking about about we could take advantage of Deno and various other improvements.

Great idea!

**Comment by springcomp** [comment]
@cawalch  I have sent you an invite to the JmesPath Community organization.

**Pull request merged**
